import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn' | 'ml' | 'pa';

interface LanguageOption {
  code: Language;
  name: string;
  nativeName: string;
}

export const languages: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

type TranslationKey = 
  | 'appName' | 'disclaimer' | 'welcomeBack' | 'signIn' | 'signUp' | 'email' | 'password' 
  | 'confirmPassword' | 'forgotPassword' | 'noAccount' | 'hasAccount' | 'createAccount'
  | 'getStarted' | 'next' | 'back' | 'save' | 'cancel' | 'done' | 'skip'
  | 'onboardingTitle' | 'onboardingSubtitle' | 'childName' | 'childAge' | 'years' | 'months'
  | 'behavioralInfo' | 'developmentalInfo' | 'communicationLevel' | 'sensoryPreferences'
  | 'dashboard' | 'dailyLog' | 'behaviors' | 'medications' | 'summary' | 'settings'
  | 'logRoutine' | 'sleep' | 'food' | 'activities' | 'therapy' | 'notes'
  | 'reportChange' | 'suddenChange' | 'unusualBehavior' | 'supportiveSuggestions'
  | 'medicationReminder' | 'addMedication' | 'medicationName' | 'time' | 'frequency'
  | 'dailySummary' | 'todaysSummary' | 'weeklyOverview' | 'positiveNotes'
  | 'selectLanguage' | 'profile' | 'logout' | 'today' | 'thisWeek'
  | 'voiceInput' | 'textInput' | 'startRecording' | 'stopRecording'
  | 'verbal' | 'nonVerbal' | 'limited' | 'developing'
  | 'high' | 'moderate' | 'low' | 'seeking' | 'avoiding'
  | 'selectRole' | 'parent' | 'therapist' | 'parentDesc' | 'therapistDesc'
  | 'qualification' | 'specialization' | 'registrationNumber' | 'clinicName' | 'uploadCertificate' | 'uploadLicense'
  | 'verificationPending' | 'verifiedTherapist' | 'pendingVerification';

type Translations = Record<TranslationKey, string>;

const translations: Record<Language, Translations> = {
  en: {
    appName: 'AutismCare',
    disclaimer: 'This system is a decision-support tool and does not replace therapists or doctors.',
    welcomeBack: 'Welcome Back',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    createAccount: 'Create Account',
    getStarted: 'Get Started',
    next: 'Next',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    done: 'Done',
    skip: 'Skip',
    onboardingTitle: "Let's personalize your experience",
    onboardingSubtitle: 'This information helps us provide relevant support',
    childName: "Child's Name",
    childAge: "Child's Age",
    years: 'years',
    months: 'months',
    behavioralInfo: 'Behavioral Information',
    developmentalInfo: 'Developmental Information',
    communicationLevel: 'Communication Level',
    sensoryPreferences: 'Sensory Preferences',
    dashboard: 'Dashboard',
    dailyLog: 'Daily Log',
    behaviors: 'Behaviors',
    medications: 'Medications',
    summary: 'Summary',
    settings: 'Settings',
    logRoutine: 'Log Routine',
    sleep: 'Sleep',
    food: 'Food',
    activities: 'Activities',
    therapy: 'Therapy',
    notes: 'Notes',
    reportChange: 'Report Change',
    suddenChange: 'Sudden Change',
    unusualBehavior: 'Unusual Behavior',
    supportiveSuggestions: 'Supportive Suggestions',
    medicationReminder: 'Medication Reminder',
    addMedication: 'Add Medication',
    medicationName: 'Medication Name',
    time: 'Time',
    frequency: 'Frequency',
    dailySummary: 'Daily Summary',
    todaysSummary: "Today's Summary",
    weeklyOverview: 'Weekly Overview',
    positiveNotes: 'Positive Notes',
    selectLanguage: 'Select Language',
    profile: 'Profile',
    logout: 'Logout',
    today: 'Today',
    thisWeek: 'This Week',
    voiceInput: 'Voice Input',
    textInput: 'Text Input',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    verbal: 'Verbal',
    nonVerbal: 'Non-Verbal',
    limited: 'Limited',
    developing: 'Developing',
    high: 'High',
    moderate: 'Moderate',
    low: 'Low',
    seeking: 'Seeking',
    avoiding: 'Avoiding',
    selectRole: 'I am a',
    parent: 'Parent / Caregiver',
    therapist: 'Therapist',
    parentDesc: 'Track daily routines, behaviors, and share with therapists',
    therapistDesc: 'View shared reports and collaborate with parents',
    qualification: 'Qualification',
    specialization: 'Specialization',
    registrationNumber: 'Registration / License Number',
    clinicName: 'Clinic / Hospital Name',
    uploadCertificate: 'Upload Degree Certificate',
    uploadLicense: 'Upload Professional License',
    verificationPending: 'Verification Pending',
    verifiedTherapist: 'Verified Therapist',
    pendingVerification: 'Pending Verification',
  },
  hi: {
    appName: 'ऑटिज़्म केयर',
    disclaimer: 'यह प्रणाली एक निर्णय-समर्थन उपकरण है और चिकित्सकों या डॉक्टरों का विकल्प नहीं है।',
    welcomeBack: 'वापसी पर स्वागत है',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    forgotPassword: 'पासवर्ड भूल गए?',
    noAccount: 'खाता नहीं है?',
    hasAccount: 'पहले से खाता है?',
    createAccount: 'खाता बनाएं',
    getStarted: 'शुरू करें',
    next: 'अगला',
    back: 'पीछे',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    done: 'हो गया',
    skip: 'छोड़ें',
    onboardingTitle: 'आइए आपके अनुभव को वैयक्तिकृत करें',
    onboardingSubtitle: 'यह जानकारी हमें प्रासंगिक सहायता प्रदान करने में मदद करती है',
    childName: 'बच्चे का नाम',
    childAge: 'बच्चे की उम्र',
    years: 'वर्ष',
    months: 'महीने',
    behavioralInfo: 'व्यवहार संबंधी जानकारी',
    developmentalInfo: 'विकास संबंधी जानकारी',
    communicationLevel: 'संचार स्तर',
    sensoryPreferences: 'संवेदी प्राथमिकताएं',
    dashboard: 'डैशबोर्ड',
    dailyLog: 'दैनिक लॉग',
    behaviors: 'व्यवहार',
    medications: 'दवाइयां',
    summary: 'सारांश',
    settings: 'सेटिंग्स',
    logRoutine: 'दिनचर्या लॉग करें',
    sleep: 'नींद',
    food: 'भोजन',
    activities: 'गतिविधियां',
    therapy: 'थेरेपी',
    notes: 'नोट्स',
    reportChange: 'बदलाव की रिपोर्ट करें',
    suddenChange: 'अचानक बदलाव',
    unusualBehavior: 'असामान्य व्यवहार',
    supportiveSuggestions: 'सहायक सुझाव',
    medicationReminder: 'दवा की याद',
    addMedication: 'दवा जोड़ें',
    medicationName: 'दवा का नाम',
    time: 'समय',
    frequency: 'आवृत्ति',
    dailySummary: 'दैनिक सारांश',
    todaysSummary: 'आज का सारांश',
    weeklyOverview: 'साप्ताहिक अवलोकन',
    positiveNotes: 'सकारात्मक नोट्स',
    selectLanguage: 'भाषा चुनें',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉग आउट',
    today: 'आज',
    thisWeek: 'इस सप्ताह',
    voiceInput: 'आवाज़ इनपुट',
    textInput: 'टेक्स्ट इनपुट',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    verbal: 'मौखिक',
    nonVerbal: 'गैर-मौखिक',
    limited: 'सीमित',
    developing: 'विकासशील',
    high: 'उच्च',
    moderate: 'मध्यम',
    low: 'कम',
    seeking: 'खोजना',
    avoiding: 'टालना',
  },
  ta: {
    appName: 'ஆட்டிசம் கேர்',
    disclaimer: 'இந்த அமைப்பு ஒரு முடிவு-ஆதரவு கருவி மற்றும் சிகிச்சையாளர்கள் அல்லது மருத்துவர்களை மாற்றாது.',
    welcomeBack: 'மீண்டும் வருக',
    signIn: 'உள்நுழைக',
    signUp: 'பதிவு செய்க',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    forgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    noAccount: 'கணக்கு இல்லையா?',
    hasAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    createAccount: 'கணக்கை உருவாக்கு',
    getStarted: 'தொடங்குங்கள்',
    next: 'அடுத்து',
    back: 'பின்',
    save: 'சேமி',
    cancel: 'ரத்து',
    done: 'முடிந்தது',
    skip: 'தவிர்',
    onboardingTitle: 'உங்கள் அனுபவத்தை தனிப்பயனாக்குவோம்',
    onboardingSubtitle: 'இந்த தகவல் பொருத்தமான ஆதரவை வழங்க உதவுகிறது',
    childName: 'குழந்தையின் பெயர்',
    childAge: 'குழந்தையின் வயது',
    years: 'ஆண்டுகள்',
    months: 'மாதங்கள்',
    behavioralInfo: 'நடத்தை தகவல்',
    developmentalInfo: 'வளர்ச்சி தகவல்',
    communicationLevel: 'தொடர்பு நிலை',
    sensoryPreferences: 'உணர்வு விருப்பங்கள்',
    dashboard: 'டாஷ்போர்டு',
    dailyLog: 'தினசரி பதிவு',
    behaviors: 'நடத்தைகள்',
    medications: 'மருந்துகள்',
    summary: 'சுருக்கம்',
    settings: 'அமைப்புகள்',
    logRoutine: 'வழக்கத்தை பதிவு செய்',
    sleep: 'தூக்கம்',
    food: 'உணவு',
    activities: 'செயல்பாடுகள்',
    therapy: 'சிகிச்சை',
    notes: 'குறிப்புகள்',
    reportChange: 'மாற்றத்தை புகாரளி',
    suddenChange: 'திடீர் மாற்றம்',
    unusualBehavior: 'அசாதாரண நடத்தை',
    supportiveSuggestions: 'ஆதரவு பரிந்துரைகள்',
    medicationReminder: 'மருந்து நினைவூட்டல்',
    addMedication: 'மருந்து சேர்',
    medicationName: 'மருந்து பெயர்',
    time: 'நேரம்',
    frequency: 'அதிர்வெண்',
    dailySummary: 'தினசரி சுருக்கம்',
    todaysSummary: 'இன்றைய சுருக்கம்',
    weeklyOverview: 'வாராந்திர மேலோட்டம்',
    positiveNotes: 'நேர்மறை குறிப்புகள்',
    selectLanguage: 'மொழி தேர்வு',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    today: 'இன்று',
    thisWeek: 'இந்த வாரம்',
    voiceInput: 'குரல் உள்ளீடு',
    textInput: 'உரை உள்ளீடு',
    startRecording: 'பதிவைத் தொடங்கு',
    stopRecording: 'பதிவை நிறுத்து',
    verbal: 'வாய்மொழி',
    nonVerbal: 'வாய்மொழி அல்லாத',
    limited: 'வரையறுக்கப்பட்ட',
    developing: 'வளர்ந்து வரும்',
    high: 'உயர்',
    moderate: 'மிதமான',
    low: 'குறைந்த',
    seeking: 'தேடுதல்',
    avoiding: 'தவிர்த்தல்',
  },
  te: {
    appName: 'ఆటిజం కేర్',
    disclaimer: 'ఈ వ్యవస్థ ఒక నిర్ణయ-మద్దతు సాధనం మరియు థెరపిస్టులు లేదా వైద్యులను భర్తీ చేయదు.',
    welcomeBack: 'తిరిగి స్వాగతం',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    confirmPassword: 'పాస్‌వర్డ్ నిర్ధారించండి',
    forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    noAccount: 'ఖాతా లేదా?',
    hasAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    createAccount: 'ఖాతా సృష్టించండి',
    getStarted: 'ప్రారంభించండి',
    next: 'తదుపరి',
    back: 'వెనుక',
    save: 'సేవ్ చేయండి',
    cancel: 'రద్దు',
    done: 'పూర్తయింది',
    skip: 'దాటవేయి',
    onboardingTitle: 'మీ అనుభవాన్ని వ్యక్తిగతీకరించండి',
    onboardingSubtitle: 'ఈ సమాచారం సంబంధిత మద్దతు అందించడంలో సహాయపడుతుంది',
    childName: 'పిల్లల పేరు',
    childAge: 'పిల్లల వయస్సు',
    years: 'సంవత్సరాలు',
    months: 'నెలలు',
    behavioralInfo: 'ప్రవర్తన సమాచారం',
    developmentalInfo: 'అభివృద్ధి సమాచారం',
    communicationLevel: 'కమ్యూనికేషన్ స్థాయి',
    sensoryPreferences: 'ఇంద్రియ ప్రాధాన్యతలు',
    dashboard: 'డాష్‌బోర్డ్',
    dailyLog: 'రోజువారీ లాగ్',
    behaviors: 'ప్రవర్తనలు',
    medications: 'మందులు',
    summary: 'సారాంశం',
    settings: 'సెట్టింగ్‌లు',
    logRoutine: 'రొటీన్ లాగ్ చేయండి',
    sleep: 'నిద్ర',
    food: 'ఆహారం',
    activities: 'కార్యకలాపాలు',
    therapy: 'థెరపీ',
    notes: 'గమనికలు',
    reportChange: 'మార్పు నివేదించండి',
    suddenChange: 'అకస్మాత్తు మార్పు',
    unusualBehavior: 'అసాధారణ ప్రవర్తన',
    supportiveSuggestions: 'సహాయక సూచనలు',
    medicationReminder: 'మందుల రిమైండర్',
    addMedication: 'మందు జోడించండి',
    medicationName: 'మందు పేరు',
    time: 'సమయం',
    frequency: 'ఫ్రీక్వెన్సీ',
    dailySummary: 'రోజువారీ సారాంశం',
    todaysSummary: 'నేటి సారాంశం',
    weeklyOverview: 'వారపు అవలోకనం',
    positiveNotes: 'సానుకూల గమనికలు',
    selectLanguage: 'భాష ఎంచుకోండి',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    today: 'ఈ రోజు',
    thisWeek: 'ఈ వారం',
    voiceInput: 'వాయిస్ ఇన్‌పుట్',
    textInput: 'టెక్స్ట్ ఇన్‌పుట్',
    startRecording: 'రికార్డింగ్ ప్రారంభించండి',
    stopRecording: 'రికార్డింగ్ ఆపండి',
    verbal: 'మౌఖిక',
    nonVerbal: 'మౌఖిక కాని',
    limited: 'పరిమిత',
    developing: 'అభివృద్ధి చెందుతున్న',
    high: 'అధిక',
    moderate: 'మధ్యస్థ',
    low: 'తక్కువ',
    seeking: 'కోరుకునే',
    avoiding: 'నివారించే',
  },
  bn: {
    appName: 'অটিজম কেয়ার',
    disclaimer: 'এই সিস্টেম একটি সিদ্ধান্ত-সহায়তা সরঞ্জাম এবং থেরাপিস্ট বা ডাক্তারদের প্রতিস্থাপন করে না।',
    welcomeBack: 'স্বাগতম',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    email: 'ইমেল',
    password: 'পাসওয়ার্ড',
    confirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    noAccount: 'অ্যাকাউন্ট নেই?',
    hasAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    createAccount: 'অ্যাকাউন্ট তৈরি করুন',
    getStarted: 'শুরু করুন',
    next: 'পরবর্তী',
    back: 'পিছনে',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    done: 'সম্পন্ন',
    skip: 'এড়িয়ে যান',
    onboardingTitle: 'আপনার অভিজ্ঞতা ব্যক্তিগতকৃত করুন',
    onboardingSubtitle: 'এই তথ্য প্রাসঙ্গিক সহায়তা প্রদানে সাহায্য করে',
    childName: 'শিশুর নাম',
    childAge: 'শিশুর বয়স',
    years: 'বছর',
    months: 'মাস',
    behavioralInfo: 'আচরণগত তথ্য',
    developmentalInfo: 'উন্নয়নমূলক তথ্য',
    communicationLevel: 'যোগাযোগ স্তর',
    sensoryPreferences: 'সংবেদনশীল পছন্দ',
    dashboard: 'ড্যাশবোর্ড',
    dailyLog: 'দৈনিক লগ',
    behaviors: 'আচরণ',
    medications: 'ওষুধ',
    summary: 'সারসংক্ষেপ',
    settings: 'সেটিংস',
    logRoutine: 'রুটিন লগ করুন',
    sleep: 'ঘুম',
    food: 'খাবার',
    activities: 'কার্যকলাপ',
    therapy: 'থেরাপি',
    notes: 'নোট',
    reportChange: 'পরিবর্তন রিপোর্ট করুন',
    suddenChange: 'আকস্মিক পরিবর্তন',
    unusualBehavior: 'অস্বাভাবিক আচরণ',
    supportiveSuggestions: 'সহায়ক পরামর্শ',
    medicationReminder: 'ওষুধ রিমাইন্ডার',
    addMedication: 'ওষুধ যোগ করুন',
    medicationName: 'ওষুধের নাম',
    time: 'সময়',
    frequency: 'ফ্রিকোয়েন্সি',
    dailySummary: 'দৈনিক সারসংক্ষেপ',
    todaysSummary: 'আজকের সারসংক্ষেপ',
    weeklyOverview: 'সাপ্তাহিক ওভারভিউ',
    positiveNotes: 'ইতিবাচক নোট',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    profile: 'প্রোফাইল',
    logout: 'লগ আউট',
    today: 'আজ',
    thisWeek: 'এই সপ্তাহ',
    voiceInput: 'ভয়েস ইনপুট',
    textInput: 'টেক্সট ইনপুট',
    startRecording: 'রেকর্ডিং শুরু করুন',
    stopRecording: 'রেকর্ডিং বন্ধ করুন',
    verbal: 'মৌখিক',
    nonVerbal: 'অ-মৌখিক',
    limited: 'সীমিত',
    developing: 'উন্নয়নশীল',
    high: 'উচ্চ',
    moderate: 'মধ্যম',
    low: 'নিম্ন',
    seeking: 'খোঁজা',
    avoiding: 'এড়ানো',
  },
  mr: {
    appName: 'ऑटिझम केअर',
    disclaimer: 'ही प्रणाली एक निर्णय-समर्थन साधन आहे आणि थेरपिस्ट किंवा डॉक्टरांची जागा घेत नाही.',
    welcomeBack: 'पुन्हा स्वागत',
    signIn: 'साइन इन करा',
    signUp: 'साइन अप करा',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्डची पुष्टी करा',
    forgotPassword: 'पासवर्ड विसरलात?',
    noAccount: 'खाते नाही?',
    hasAccount: 'आधीच खाते आहे?',
    createAccount: 'खाते तयार करा',
    getStarted: 'सुरू करा',
    next: 'पुढे',
    back: 'मागे',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    done: 'पूर्ण',
    skip: 'वगळा',
    onboardingTitle: 'तुमचा अनुभव वैयक्तिकृत करा',
    onboardingSubtitle: 'ही माहिती संबंधित समर्थन प्रदान करण्यात मदत करते',
    childName: 'मुलाचे नाव',
    childAge: 'मुलाचे वय',
    years: 'वर्षे',
    months: 'महिने',
    behavioralInfo: 'वर्तणूक माहिती',
    developmentalInfo: 'विकास माहिती',
    communicationLevel: 'संवाद पातळी',
    sensoryPreferences: 'संवेदी प्राधान्ये',
    dashboard: 'डॅशबोर्ड',
    dailyLog: 'दैनंदिन लॉग',
    behaviors: 'वर्तणूक',
    medications: 'औषधे',
    summary: 'सारांश',
    settings: 'सेटिंग्ज',
    logRoutine: 'दिनक्रम लॉग करा',
    sleep: 'झोप',
    food: 'अन्न',
    activities: 'क्रियाकलाप',
    therapy: 'थेरपी',
    notes: 'टिपा',
    reportChange: 'बदल कळवा',
    suddenChange: 'अचानक बदल',
    unusualBehavior: 'असामान्य वर्तणूक',
    supportiveSuggestions: 'सहाय्यक सूचना',
    medicationReminder: 'औषध स्मरणपत्र',
    addMedication: 'औषध जोडा',
    medicationName: 'औषधाचे नाव',
    time: 'वेळ',
    frequency: 'वारंवारता',
    dailySummary: 'दैनंदिन सारांश',
    todaysSummary: 'आजचा सारांश',
    weeklyOverview: 'साप्ताहिक आढावा',
    positiveNotes: 'सकारात्मक टिपा',
    selectLanguage: 'भाषा निवडा',
    profile: 'प्रोफाइल',
    logout: 'लॉग आउट',
    today: 'आज',
    thisWeek: 'या आठवड्यात',
    voiceInput: 'व्हॉइस इनपुट',
    textInput: 'मजकूर इनपुट',
    startRecording: 'रेकॉर्डिंग सुरू करा',
    stopRecording: 'रेकॉर्डिंग थांबवा',
    verbal: 'तोंडी',
    nonVerbal: 'अतोंडी',
    limited: 'मर्यादित',
    developing: 'विकसनशील',
    high: 'उच्च',
    moderate: 'मध्यम',
    low: 'कमी',
    seeking: 'शोधत आहे',
    avoiding: 'टाळत आहे',
  },
  gu: {
    appName: 'ઓટિઝમ કેર',
    disclaimer: 'આ સિસ્ટમ એક નિર્ણય-સહાય સાધન છે અને થેરાપિસ્ટ અથવા ડોક્ટરોની જગ્યા લેતી નથી.',
    welcomeBack: 'ફરીથી સ્વાગત છે',
    signIn: 'સાઇન ઇન',
    signUp: 'સાઇન અપ',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    confirmPassword: 'પાસવર્ડ કન્ફર્મ કરો',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા?',
    noAccount: 'એકાઉન્ટ નથી?',
    hasAccount: 'પહેલેથી એકાઉન્ટ છે?',
    createAccount: 'એકાઉન્ટ બનાવો',
    getStarted: 'શરૂ કરો',
    next: 'આગળ',
    back: 'પાછળ',
    save: 'સાચવો',
    cancel: 'રદ કરો',
    done: 'પૂર્ણ',
    skip: 'છોડો',
    onboardingTitle: 'તમારા અનુભવને વ્યક્તિગત બનાવો',
    onboardingSubtitle: 'આ માહિતી સંબંધિત સહાય પ્રદાન કરવામાં મદદ કરે છે',
    childName: 'બાળકનું નામ',
    childAge: 'બાળકની ઉંમર',
    years: 'વર્ષ',
    months: 'મહિના',
    behavioralInfo: 'વર્તણૂકની માહિતી',
    developmentalInfo: 'વિકાસની માહિતી',
    communicationLevel: 'સંવાદ સ્તર',
    sensoryPreferences: 'સંવેદનાત્મક પસંદગીઓ',
    dashboard: 'ડેશબોર્ડ',
    dailyLog: 'દૈનિક લોગ',
    behaviors: 'વર્તણૂક',
    medications: 'દવાઓ',
    summary: 'સારાંશ',
    settings: 'સેટિંગ્સ',
    logRoutine: 'રૂટિન લોગ કરો',
    sleep: 'ઊંઘ',
    food: 'ખોરાક',
    activities: 'પ્રવૃત્તિઓ',
    therapy: 'થેરાપી',
    notes: 'નોંધ',
    reportChange: 'ફેરફાર રિપોર્ટ કરો',
    suddenChange: 'અચાનક ફેરફાર',
    unusualBehavior: 'અસામાન્ય વર્તન',
    supportiveSuggestions: 'સહાયક સૂચનો',
    medicationReminder: 'દવા રિમાઇન્ડર',
    addMedication: 'દવા ઉમેરો',
    medicationName: 'દવાનું નામ',
    time: 'સમય',
    frequency: 'આવર્તન',
    dailySummary: 'દૈનિક સારાંશ',
    todaysSummary: 'આજનો સારાંશ',
    weeklyOverview: 'સાપ્તાહિક ઝાંખી',
    positiveNotes: 'હકારાત્મક નોંધ',
    selectLanguage: 'ભાષા પસંદ કરો',
    profile: 'પ્રોફાઇલ',
    logout: 'લોગ આઉટ',
    today: 'આજે',
    thisWeek: 'આ સપ્તાહ',
    voiceInput: 'વૉઇસ ઇનપુટ',
    textInput: 'ટેક્સ્ટ ઇનપુટ',
    startRecording: 'રેકોર્ડિંગ શરૂ કરો',
    stopRecording: 'રેકોર્ડિંગ બંધ કરો',
    verbal: 'મૌખિક',
    nonVerbal: 'બિન-મૌખિક',
    limited: 'મર્યાદિત',
    developing: 'વિકસિત થતું',
    high: 'ઉચ્ચ',
    moderate: 'મધ્યમ',
    low: 'નીચું',
    seeking: 'શોધવું',
    avoiding: 'ટાળવું',
  },
  kn: {
    appName: 'ಆಟಿಸಂ ಕೇರ್',
    disclaimer: 'ಈ ವ್ಯವಸ್ಥೆ ನಿರ್ಧಾರ-ಬೆಂಬಲ ಸಾಧನವಾಗಿದೆ ಮತ್ತು ಚಿಕಿತ್ಸಕರು ಅಥವಾ ವೈದ್ಯರನ್ನು ಬದಲಿಸುವುದಿಲ್ಲ.',
    welcomeBack: 'ಮರಳಿ ಸ್ವಾಗತ',
    signIn: 'ಸೈನ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್ವರ್ಡ್',
    confirmPassword: 'ಪಾಸ್ವರ್ಡ್ ಖಚಿತಪಡಿಸಿ',
    forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?',
    noAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    hasAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    createAccount: 'ಖಾತೆ ರಚಿಸಿ',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    next: 'ಮುಂದೆ',
    back: 'ಹಿಂದೆ',
    save: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದುಮಾಡಿ',
    done: 'ಮುಗಿದಿದೆ',
    skip: 'ಬಿಟ್ಟುಬಿಡಿ',
    onboardingTitle: 'ನಿಮ್ಮ ಅನುಭವವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಿ',
    onboardingSubtitle: 'ಈ ಮಾಹಿತಿ ಸಂಬಂಧಿತ ಬೆಂಬಲ ಒದಗಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ',
    childName: 'ಮಗುವಿನ ಹೆಸರು',
    childAge: 'ಮಗುವಿನ ವಯಸ್ಸು',
    years: 'ವರ್ಷಗಳು',
    months: 'ತಿಂಗಳುಗಳು',
    behavioralInfo: 'ವರ್ತನಾ ಮಾಹಿತಿ',
    developmentalInfo: 'ಅಭಿವೃದ್ಧಿ ಮಾಹಿತಿ',
    communicationLevel: 'ಸಂವಹನ ಮಟ್ಟ',
    sensoryPreferences: 'ಸಂವೇದನಾ ಆದ್ಯತೆಗಳು',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    dailyLog: 'ದೈನಂದಿನ ಲಾಗ್',
    behaviors: 'ವರ್ತನೆಗಳು',
    medications: 'ಔಷಧಗಳು',
    summary: 'ಸಾರಾಂಶ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logRoutine: 'ದಿನಚರಿ ಲಾಗ್ ಮಾಡಿ',
    sleep: 'ನಿದ್ರೆ',
    food: 'ಆಹಾರ',
    activities: 'ಚಟುವಟಿಕೆಗಳು',
    therapy: 'ಚಿಕಿತ್ಸೆ',
    notes: 'ಟಿಪ್ಪಣಿಗಳು',
    reportChange: 'ಬದಲಾವಣೆ ವರದಿ ಮಾಡಿ',
    suddenChange: 'ತಿಪಿನ ಬದಲಾವಣೆ',
    unusualBehavior: 'ಅಸಾಮಾನ್ಯ ವರ್ತನೆ',
    supportiveSuggestions: 'ಬೆಂಬಲ ಸಲಹೆಗಳು',
    medicationReminder: 'ಔಷಧ ರಿಮೈಂಡರ್',
    addMedication: 'ಔಷಧ ಸೇರಿಸಿ',
    medicationName: 'ಔಷಧದ ಹೆಸರು',
    time: 'ಸಮಯ',
    frequency: 'ಆವರ್ತನ',
    dailySummary: 'ದೈನಂದಿನ ಸಾರಾಂಶ',
    todaysSummary: 'ಇಂದಿನ ಸಾರಾಂಶ',
    weeklyOverview: 'ವಾರದ ಅವಲೋಕನ',
    positiveNotes: 'ಧನಾತ್ಮಕ ಟಿಪ್ಪಣಿಗಳು',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    today: 'ಇಂದು',
    thisWeek: 'ಈ ವಾರ',
    voiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    textInput: 'ಪಠ್ಯ ಇನ್‌ಪುಟ್',
    startRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    stopRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    verbal: 'ಮೌಖಿಕ',
    nonVerbal: 'ಅಮೌಖಿಕ',
    limited: 'ಸೀಮಿತ',
    developing: 'ಅಭಿವೃದ್ಧಿ ಹೊಂದುತ್ತಿದೆ',
    high: 'ಹೆಚ್ಚು',
    moderate: 'ಮಧ್ಯಮ',
    low: 'ಕಡಿಮೆ',
    seeking: 'ಹುಡುಕುವ',
    avoiding: 'ತಪ್ಪಿಸುವ',
  },
  ml: {
    appName: 'ഓട്ടിസം കെയർ',
    disclaimer: 'ഈ സിസ്റ്റം ഒരു തീരുമാന-പിന്തുണ ഉപകരണമാണ്, തെറാപ്പിസ്റ്റുകളെയോ ഡോക്ടർമാരെയോ മാറ്റിസ്ഥാപിക്കുന്നില്ല.',
    welcomeBack: 'വീണ്ടും സ്വാഗതം',
    signIn: 'സൈൻ ഇൻ',
    signUp: 'സൈൻ അപ്പ്',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    confirmPassword: 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    forgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    noAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    hasAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    createAccount: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    getStarted: 'ആരംഭിക്കുക',
    next: 'അടുത്തത്',
    back: 'പിന്നിലേക്ക്',
    save: 'സേവ് ചെയ്യുക',
    cancel: 'റദ്ദാക്കുക',
    done: 'പൂർത്തിയായി',
    skip: 'ഒഴിവാക്കുക',
    onboardingTitle: 'നിങ്ങളുടെ അനുഭവം വ്യക്തിഗതമാക്കുക',
    onboardingSubtitle: 'ഈ വിവരങ്ങൾ പ്രസക്തമായ പിന്തുണ നൽകാൻ സഹായിക്കുന്നു',
    childName: 'കുട്ടിയുടെ പേര്',
    childAge: 'കുട്ടിയുടെ പ്രായം',
    years: 'വർഷങ്ങൾ',
    months: 'മാസങ്ങൾ',
    behavioralInfo: 'പെരുമാറ്റ വിവരങ്ങൾ',
    developmentalInfo: 'വികസന വിവരങ്ങൾ',
    communicationLevel: 'ആശയവിനിമയ നില',
    sensoryPreferences: 'സെൻസറി മുൻഗണനകൾ',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    dailyLog: 'ദൈനംദിന ലോഗ്',
    behaviors: 'പെരുമാറ്റങ്ങൾ',
    medications: 'മരുന്നുകൾ',
    summary: 'സംഗ്രഹം',
    settings: 'ക്രമീകരണങ്ങൾ',
    logRoutine: 'ദിനചര്യ ലോഗ് ചെയ്യുക',
    sleep: 'ഉറക്കം',
    food: 'ഭക്ഷണം',
    activities: 'പ്രവർത്തനങ്ങൾ',
    therapy: 'തെറാപ്പി',
    notes: 'കുറിപ്പുകൾ',
    reportChange: 'മാറ്റം റിപ്പോർട്ട് ചെയ്യുക',
    suddenChange: 'പെട്ടെന്നുള്ള മാറ്റം',
    unusualBehavior: 'അസാധാരണ പെരുമാറ്റം',
    supportiveSuggestions: 'പിന്തുണാ നിർദ്ദേശങ്ങൾ',
    medicationReminder: 'മരുന്ന് ഓർമ്മപ്പെടുത്തൽ',
    addMedication: 'മരുന്ന് ചേർക്കുക',
    medicationName: 'മരുന്നിന്റെ പേര്',
    time: 'സമയം',
    frequency: 'ആവർത്തനം',
    dailySummary: 'ദൈനംദിന സംഗ്രഹം',
    todaysSummary: 'ഇന്നത്തെ സംഗ്രഹം',
    weeklyOverview: 'ആഴ്ചയിലെ അവലോകനം',
    positiveNotes: 'പോസിറ്റീവ് കുറിപ്പുകൾ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    profile: 'പ്രൊഫൈൽ',
    logout: 'ലോഗ് ഔട്ട്',
    today: 'ഇന്ന്',
    thisWeek: 'ഈ ആഴ്ച',
    voiceInput: 'വോയ്സ് ഇൻപുട്ട്',
    textInput: 'ടെക്സ്റ്റ് ഇൻപുട്ട്',
    startRecording: 'റെക്കോർഡിംഗ് ആരംഭിക്കുക',
    stopRecording: 'റെക്കോർഡിംഗ് നിർത്തുക',
    verbal: 'വാമൊഴി',
    nonVerbal: 'അവാമൊഴി',
    limited: 'പരിമിതമായ',
    developing: 'വികസിക്കുന്ന',
    high: 'ഉയർന്ന',
    moderate: 'മിതമായ',
    low: 'താഴ്ന്ന',
    seeking: 'അന്വേഷിക്കുന്ന',
    avoiding: 'ഒഴിവാക്കുന്ന',
  },
  pa: {
    appName: 'ਔਟਿਜ਼ਮ ਕੇਅਰ',
    disclaimer: 'ਇਹ ਪ੍ਰਣਾਲੀ ਇੱਕ ਫੈਸਲੇ-ਸਹਾਇਤਾ ਸਾਧਨ ਹੈ ਅਤੇ ਥੈਰੇਪਿਸਟਾਂ ਜਾਂ ਡਾਕਟਰਾਂ ਦੀ ਥਾਂ ਨਹੀਂ ਲੈਂਦੀ।',
    welcomeBack: 'ਵਾਪਸੀ ਤੇ ਜੀ ਆਇਆਂ ਨੂੰ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signUp: 'ਸਾਈਨ ਅੱਪ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    noAccount: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    hasAccount: 'ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?',
    createAccount: 'ਖਾਤਾ ਬਣਾਓ',
    getStarted: 'ਸ਼ੁਰੂ ਕਰੋ',
    next: 'ਅੱਗੇ',
    back: 'ਪਿੱਛੇ',
    save: 'ਸੇਵ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    done: 'ਹੋ ਗਿਆ',
    skip: 'ਛੱਡੋ',
    onboardingTitle: 'ਆਪਣੇ ਤਜਰਬੇ ਨੂੰ ਨਿੱਜੀ ਬਣਾਓ',
    onboardingSubtitle: 'ਇਹ ਜਾਣਕਾਰੀ ਢੁਕਵੀਂ ਸਹਾਇਤਾ ਪ੍ਰਦਾਨ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦੀ ਹੈ',
    childName: 'ਬੱਚੇ ਦਾ ਨਾਮ',
    childAge: 'ਬੱਚੇ ਦੀ ਉਮਰ',
    years: 'ਸਾਲ',
    months: 'ਮਹੀਨੇ',
    behavioralInfo: 'ਵਿਵਹਾਰ ਸੰਬੰਧੀ ਜਾਣਕਾਰੀ',
    developmentalInfo: 'ਵਿਕਾਸ ਸੰਬੰਧੀ ਜਾਣਕਾਰੀ',
    communicationLevel: 'ਸੰਚਾਰ ਪੱਧਰ',
    sensoryPreferences: 'ਸੰਵੇਦੀ ਤਰਜੀਹਾਂ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    dailyLog: 'ਰੋਜ਼ਾਨਾ ਲੌਗ',
    behaviors: 'ਵਿਵਹਾਰ',
    medications: 'ਦਵਾਈਆਂ',
    summary: 'ਸੰਖੇਪ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    logRoutine: 'ਰੂਟੀਨ ਲੌਗ ਕਰੋ',
    sleep: 'ਨੀਂਦ',
    food: 'ਖਾਣਾ',
    activities: 'ਗਤੀਵਿਧੀਆਂ',
    therapy: 'ਥੈਰੇਪੀ',
    notes: 'ਨੋਟਸ',
    reportChange: 'ਬਦਲਾਅ ਰਿਪੋਰਟ ਕਰੋ',
    suddenChange: 'ਅਚਾਨਕ ਬਦਲਾਅ',
    unusualBehavior: 'ਅਸਾਧਾਰਨ ਵਿਵਹਾਰ',
    supportiveSuggestions: 'ਸਹਾਇਕ ਸੁਝਾਅ',
    medicationReminder: 'ਦਵਾਈ ਰੀਮਾਈਂਡਰ',
    addMedication: 'ਦਵਾਈ ਸ਼ਾਮਲ ਕਰੋ',
    medicationName: 'ਦਵਾਈ ਦਾ ਨਾਮ',
    time: 'ਸਮਾਂ',
    frequency: 'ਬਾਰੰਬਾਰਤਾ',
    dailySummary: 'ਰੋਜ਼ਾਨਾ ਸੰਖੇਪ',
    todaysSummary: 'ਅੱਜ ਦਾ ਸੰਖੇਪ',
    weeklyOverview: 'ਹਫ਼ਤਾਵਾਰੀ ਸੰਖੇਪ',
    positiveNotes: 'ਸਕਾਰਾਤਮਕ ਨੋਟਸ',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    logout: 'ਲੌਗ ਆਊਟ',
    today: 'ਅੱਜ',
    thisWeek: 'ਇਸ ਹਫ਼ਤੇ',
    voiceInput: 'ਵੌਇਸ ਇਨਪੁੱਟ',
    textInput: 'ਟੈਕਸਟ ਇਨਪੁੱਟ',
    startRecording: 'ਰਿਕਾਰਡਿੰਗ ਸ਼ੁਰੂ ਕਰੋ',
    stopRecording: 'ਰਿਕਾਰਡਿੰਗ ਬੰਦ ਕਰੋ',
    verbal: 'ਮੌਖਿਕ',
    nonVerbal: 'ਗੈਰ-ਮੌਖਿਕ',
    limited: 'ਸੀਮਤ',
    developing: 'ਵਿਕਾਸਸ਼ੀਲ',
    high: 'ਉੱਚ',
    moderate: 'ਮੱਧਮ',
    low: 'ਘੱਟ',
    seeking: 'ਲੱਭਣਾ',
    avoiding: 'ਬਚਣਾ',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('autism-care-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('autism-care-language', lang);
  };

  const t = (key: TranslationKey): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
